language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: aIeJWkA1dAeqK9gU9KrVQWcM80IyCHL1HCguAD+Qxh53xgoU0TGRkIIaoOXKfC0SZn/TkjmWz1dGNL2kaGl+XsZfW9vzrzWswmoepgEzO+arQGMBZtTyu/O5x5nM2/34cQ+HqczrCls/HcXPmK2vxNx1Wb7SVkhZ2PonmC0wO6+0Hd/ur+LHidf/PK/+6wo6RJWeCzU7l4IpCnPto0wUc9K4P2a0AsRPQ1+2zRMwpeCMxRXoY8PwMM/h+A5yHpJ75m3IYSMCfNGi0FhCJX65JvdJAFJvMl6vr6/HCrlTxi+i7s9r+EDTcJDkMU05c0rtlbDXZs9TjppW24AdQDu+x8tkEEFyntdMXSkc3t603zU6oGsofEI6Zi+rEMC03EtOp9zOmDq15shh45NSJt17nTcTqij/w9PDvnrIzsj80Rz11gZiT22DwGX3698MyeeYEKDkJXm8n85s7Hsh/TNWJFXoHruPMKK8/ya1YUJBop6Y3Hd9y9QNS0DayY6ATsLqbVzbUXna/m9zZjcJKA4A6dxWUAbralDdARR8n57m94CWYLuXP/0CMIjz75ytTks1bLZwSDEdbQKTmcj19lYBzOSwJRbjIuWgo3ufCwPodKLEYUEgf/aXAaAi0b+vST4gRcSmzTdcwrH1qWBXZCosYRCnuM6dLfqwF3IMAflbh5g=
  app: still-springs-50686
  on:
    repo: jessicaerazo/maple-app
