language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: mF59G9B2xBsEOECpTHrDi3kacoY951oebtrnB2Jt93P1qn6FK0kMwdHPh2EHpEgn4W5z2obIZeQLoqJUT01IpVDLWAVXCnaJhO82Hwggs/zfdDjZdy7LuHrSgC9UiN5L2xni7u46VFaM/CgifEhwZ5zqMU5P51CNDzhvCI8CJiNz5LcEuAybbmw3S3n8S7G0+GlfhQBfe2lCR75y5iVMoG5WwizU6BrkB/pguDy7j5vcxUy7pcAoD5A3G26ThDmeBxTdQojzGN1FgqikLH1g01qxGmHPiJl7n0fBt8qUVL2WF4vx+aoveQawOvbXR0N4Nq5WhLAHqGUaCAtd1ARia9WRGu0HXUpx/o04XvbgVjCs2u8he2tD8fG5s7I+9g0LVx0yg1djDvRnvhgUh+AOBkBuK9Zfn66aJoxhd/v3f/YJRJOmF+ND5pOC2MWgD/bs3VXCGAZ03kk+oZoOED4M2jkJqRc94yvkk4B94LhJgC4rXQLIpvSBPYHh1lMNM3HnJH6uW7R16RbPMqPYim41OBY8u/7rrJ8LG6qsiRuTC2e2KEQ2bYwLDG5E/PfvPt8PsFn/f9POnhs4q3NzOPkFArEGhNkXWm5B6fYV/bnC5R1Y9E6fK1IU4QiFnTFFb109kEFSU2maW9vK0H9R/sDyyjfPYO9/l/xT8v9X2Gndo6k=
  app: maple-coupons
  on:
    repo: jessicaerazo/maple-app
