language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: S+6azMG1G2eFqyl74q8sj+CM2dpQStRnhoLTgrR95rwyFHUGjwIBe00fHZaVrTWF5Mc2SUu4cCHJCTAAtQiRPuknuXMD10Cxv7r2BhFKyJVnAERXnWN6Lt8ytUnusXDs7SdBRFQjIwbwWmoFc9oTR05smZVlWoKr3mbjfIhjfPTsSaEU1OUrjKLKGIxUOh0oGrJsdW2orJfxu9Mt/5IhP9F3VI0biKSKLI2zfAh5leLpU0e//GL6RSKcWU7vR/PH9AUc+pRfYL9T3Onjz3FEcnfv8/MylnIgdPTvC1F7iRzlmC3tRcDgB+45+RL6wgDkwEE9eG9Mogxu01JzvgYduo04Tw/+DlFk/rzIp2mglbN7ehwHDiK67nI3VhBAaT6SE3skPUzAXscntVvI2AJ7I1RVVKcz3Ek/CIXtudHs9ejKke0pukicp3hesUbKYq9XYsNGNszJoa0WrcciBYk59oYl5QsNQkGagPZHZ9i2Uk182RQpnLugUbUy6yZTYY/UHzt+7znqvM0L4Azo+Zzn36vCt5AReqASKBesvjS8jge6cD/iJJZ7X4EqyShd+yNg5mbsxNpqi6l5dJrixtKaidBvoO5rVYFGv6y9YvGSJlgBYCrxM16nA6dCgGA1suh1+fGt0j1hUi6wWrGTI3ncJM+owM50r/SKZZaTubp7wcA=
  app: maple-coupon-app
  on:
    repo: jessicaerazo/maple-app
