language: node_js
node_js: node
services:
- mongodb
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "oyvaAOsmvB++m2JXwWOsZDKqfynkWl4t3XD6YnN+Pmjfqug7qNE4zVoC04Eq0xQ8aDTJfQqT49TcyjluOcPGTueqJWR4W5l7aYoAMyFeh52cvFVcl7DRn3a5uFDL1VobHXPJ78OUWKR/q52xHmC0pmhGWkRv/JStDW6gFdAhgUEhte7wAKwDFrPqx6bbncl32l0WnnO6NOhZdB0KkQhsVIcYoHPl8PxHwtKZ9wc2uLygSndOZDg/SCWWCR/bvL171cxTNfMzXULXrZtuzXJigZpQg5cyPJRnoGRPev/vlYXQ6uXcsnHSCIhHQAMnYeqHlwyegK3uObhh9qPsGY1q8Ow6/LvezlidBz1oCRP+syS2HDSH5BkD+enjFRqRJF1BzfAG19KDV+Zy0TrGjZ3zTWQjVMVBuztUCtzlBnDKLN7KW2Som5035l1f6/QkuzExGUOtliFn60Uswbgpr6r7OAAvp1yNWVt7UpvO2gdWBMtfE1kKpjOUXwffuMXjsgR0jOB23/kgqKui7vcg+6lHBxlnTbqZbur0e2zlZqp6mKogwbScMA6uXlhwElYKSyBWO2Cw4naSeLV5KM0ed5k8euNCLuDHT6XSUMe3yruEyO+RYTzIl3K5kE+RGvK5Xq8faOD5hc94x/pN2OxHXF7YMB5Zzsr9DxYbn232zVoZtrM="
  app: still-springs-50686
  on:
    repo:
